language: python
python:
  - 2.7

# command to install miniconda
install:
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch torchvision cuda80 -c soumith
    - source activate test-environment
    - conda install --name test-environment -c anaconda numpy=1.13.1 pyyaml=3.12 pymongo=3.3.0 nose=1.3.7
    - conda install --name test-environment -c conda-forge gitpython=2.1.1
    - python setup.py install

# command to run tests
script: nosetests