State: &State !!python/name:module.State
Module: &Module !!python/name:base.Module
Status: &Status !!python/name:module.Status
Configuration: &Configuration !!python/name:module.Configuration

module_names:
    STATE_NAME: &STATE_NAME State
    MODEL_NAME: &MODEL_NAME Model
    SAVER_NAME: &SAVER_NAME Saver
    LOADER_NAME: &LOADER_NAME Loader
    # MODULE_NAME: &MODULE_NAME Module
    RUNNER_NAME: &RUNNER_NAME Runner
    STATUS_NAME: &STATUS_NAME Status
    TESTER_NAME: &TESTER_NAME Tester
    DATASET_NAME: &DATASET_NAME DataSet
    MONITOR_NAME: &MONITOR_NAME Monitor
    SAMPLER_NAME: &SAMPLER_NAME Sampler
    SESSION_NAME: &SESSION_NAME Session
    TRAINER_NAME: &TRAINER_NAME Trainer
    CRITERION_NAME: &CRITERION_NAME Criterion
    OPTIMIZER_NAME: &OPTIMIZER_NAME Optimizer
    DATALOADER_NAME: &DATALOADER_NAME DataLoader
    DATAREADER_NAME: &DATAREADER_NAME DataReader
    DBINTERFACE_NAME: &DBINTERFACE_NAME DBInterface
    DATAPROVIDER_NAME: &DATAPROVIDER_NAME DataProvider
    CONFIGURATION_NAME: &CONFIGURATION_NAME Configuration

module_bases:
    STATE_BASES: &STATE_BASES !!python/tuple [*State,]
    MODEL_BASES: &MODEL_BASES !!python/tuple [*Module,]
    SAVER_BASES: &SAVER_BASES !!python/tuple [*Module,]
    LOADER_BASES: &LOADER_BASES !!python/tuple [*Module,]
    MODULE_BASES: &MODULE_BASES !!python/tuple [*Module,]
    RUNNER_BASES: &RUNNER_BASES !!python/tuple [*Module,]
    TESTER_BASES: &TESTER_BASES !!python/tuple [*Module,]
    DATASET_BASES: &DATASET_BASES !!python/tuple [*Module,]
    MONITOR_BASES: &MONITOR_BASES !!python/tuple [*Module,]
    SAMPLER_BASES: &SAMPLER_BASES !!python/tuple [*Module,]
    SESSION_BASES: &SESSION_BASES !!python/tuple [*Module,]
    TRAINER_BASES: &TRAINER_BASES !!python/tuple [*Module,]
    CRITERION_BASES: &CRITERION_BASES !!python/tuple [*Module,]
    OPTIMIZER_BASES: &OPTIMIZER_BASES !!python/tuple [*Module,]
    DATALOADER_BASES: &DATALOADER_BASES !!python/tuple [*Module,]
    DATAREADER_BASES: &DATAREADER_BASES !!python/tuple [*Module,]
    DBINTERFACE_BASES: &DBINTERFACE_BASES !!python/tuple [*Module,]
    DATAPROVIDER_BASES: &DATAPROVIDER_BASES !!python/tuple [*Module,]
    STATUS_BASES: &STATUS_BASES !!python/tuple [*Module, *Status,]
    CONFIGURATION_BASES: &CONFIGURATION_BASES !!python/tuple [*Module, *Configuration,]

MODEL_DICT: &MODEL_DICT
    __base__: *MODEL_NAME
    __name__: *MODEL_NAME
STATE_DICT: &STATE_DICT
    __base__: *STATE_NAME
    __name__: *STATE_NAME
SAVER_DICT: &SAVER_DICT
    __base__: *SAVER_NAME
    __name__: *SAVER_NAME
LOADER_DICT: &LOADER_DICT
    __base__: *LOADER_NAME
    __name__: *LOADER_NAME
# MODULE_DICT: &MODULE_DICT
    # __base__: *MODULE_NAME
    # __name__: *MODULE_NAME
RUNNER_DICT: &RUNNER_DICT
    __base__: *RUNNER_NAME
    __name__: *RUNNER_NAME
STATUS_DICT: &STATUS_DICT
    __base__: *STATUS_NAME
    __name__: *STATUS_NAME
TESTER_DICT: &TESTER_DICT
    __base__: *TESTER_NAME
    __name__: *TESTER_NAME
DATASET_DICT: &DATASET_DICT
    __base__: *DATASET_NAME
    __name__: *DATASET_NAME
MONITOR_DICT: &MONITOR_DICT
    __base__: *MONITOR_NAME
    __name__: *MONITOR_NAME
SAMPLER_DICT: &SAMPLER_DICT
    __base__: *SAMPLER_NAME
    __name__: *SAMPLER_NAME
SESSION_DICT: &SESSION_DICT
    __base__: *SESSION_NAME
    __name__: *SESSION_NAME
TRAINER_DICT: &TRAINER_DICT
    __base__: *TRAINER_NAME
    __name__: *TRAINER_NAME
CRITERION_DICT: &CRITERION_DICT
    __base__: *CRITERION_NAME
    __name__: *CRITERION_NAME
OPTIMIZER_DICT: &OPTIMIZER_DICT
    __base__: *OPTIMIZER_NAME
    __name__: *OPTIMIZER_NAME
DATALOADER_DICT: &DATALOADER_DICT
    __base__: *DATALOADER_NAME
    __name__: *DATALOADER_NAME
DATAREADER_DICT: &DATAREADER_DICT
    __base__: *DATAREADER_NAME
    __name__: *DATAREADER_NAME
DBINTERFACE_DICT: &DBINTERFACE_DICT
    __base__: *DBINTERFACE_NAME
    __name__: *DBINTERFACE_NAME
DATAPROVIDER_DICT: &DATAPROVIDER_DICT
    __base__: *DATAPROVIDER_NAME
    __name__: *DATAPROVIDER_NAME
CONFIGURATION_DICT: &CONFIGURATION_DICT
    __base__: *CONFIGURATION_NAME
    __name__: *CONFIGURATION_NAME

BASE_MODULES:
    *MODEL_NAME: &MODEL [*MODEL_NAME, *MODEL_BASES, *MODEL_DICT]
    *STATE_NAME: &STATE [*STATE_NAME, *STATE_BASES, *STATE_DICT]
    *SAVER_NAME: &SAVER [*SAVER_NAME, *SAVER_BASES, *SAVER_DICT]
    *LOADER_NAME: &LOADER [*LOADER_NAME, *LOADER_BASES, *LOADER_DICT]
    # *MODULE_NAME: &MODULE [*MODULE_NAME, *MODULE_BASES, *MODULE_DICT]
    *RUNNER_NAME: &RUNNER [*RUNNER_NAME, *RUNNER_BASES, *RUNNER_DICT]
    *STATUS_NAME: &STATUS [*STATUS_NAME, *STATUS_BASES, *STATUS_DICT]
    *TESTER_NAME: &TESTER [*TESTER_NAME, *TESTER_BASES, *TESTER_DICT]
    *DATASET_NAME: &DATASET [*DATASET_NAME, *DATASET_BASES, *DATASET_DICT]
    *MONITOR_NAME: &MONITOR [*MONITOR_NAME, *MONITOR_BASES, *MONITOR_DICT]
    *SAMPLER_NAME: &SAMPLER [*SAMPLER_NAME, *SAMPLER_BASES, *SAMPLER_DICT]
    *SESSION_NAME: &SESSION [*SESSION_NAME, *SESSION_BASES, *SESSION_DICT]
    *TRAINER_NAME: &TRAINER [*TRAINER_NAME, *TRAINER_BASES, *TRAINER_DICT]
    *CRITERION_NAME: &CRITERION [*CRITERION_NAME, *CRITERION_BASES, *CRITERION_DICT]
    *OPTIMIZER_NAME: &OPTIMIZER [*OPTIMIZER_NAME, *OPTIMIZER_BASES, *OPTIMIZER_DICT]
    *DATALOADER_NAME: &DATALOADER [*DATALOADER_NAME, *DATALOADER_BASES, *DATALOADER_DICT]
    *DATAREADER_NAME: &DATAREADER [*DATAREADER_NAME, *DATAREADER_BASES, *DATAREADER_DICT]
    *DBINTERFACE_NAME: &DBINTERFACE [*DBINTERFACE_NAME, *DBINTERFACE_BASES, *DBINTERFACE_DICT]
    *DATAPROVIDER_NAME: &DATAPROVIDER [*DATAPROVIDER_NAME, *DATAPROVIDER_BASES, *DATAPROVIDER_DICT]
    CONFIGURATION: &CONFIGURATION [*CONFIGURATION_NAME, *CONFIGURATION_BASES, *CONFIGURATION_DICT]

# requirements:
    # Module: &Module
        # _state: *STATE
        # _configiguration: *CONFIGURATION
    # MODEL:
        # <<: *Module
        # _criterion: *CRITERION
        # _optimizer: *OPTIMIZER

# BASE_TYPES:
#     - MODEL
#     - STATE
#     - SAVER
#     - LOADER
#     - MODULE
#     - RUNNER
#     - STATUS
#     - TESTER
#     - DATASET
#     - MONITOR
#     - SAMPLER
#     - SESSION
#     - TRAINER
#     - CRITERION
#     - OPTIMIZER
#     - DATALOADER
#     - DATAREADER
#     - DBINTERFACE
#     - DATAPROVIDER
#     - CONFIGURATION

# CORE_MODULES = {
#     MODEL_NAME: Model,
#     STATE_NAME: State,
#     DBINTERFACE_NAME: DBInterface,
#     DBINTERFACE_NAME: DataProvider,
#     CONFIGURATION_NAME: Configuration,
# }

# AUX_MODULES = {
#     STATUS_NAME: Status,
#     CRITERION_NAME: Criterion,
#     OPTIMIZER_NAME: Optimizer,
# }

# Module._BASE_MODULES = BASE_MODULES
# Module._CORE_MODULES = CORE_MODULES
# Module._AUX_MODULES = AUX_MODULES
